# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0007_auto_20170918_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='country',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='subscribers',
            name='password',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='subscribers',
            name='username',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
