# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0008_auto_20171001_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribers',
            name='country',
        ),
        migrations.RemoveField(
            model_name='subscribers',
            name='email',
        ),
        migrations.AddField(
            model_name='subscribers',
            name='dpUrl',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='subscribers',
            name='photoUrl',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
