# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0009_auto_20171105_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribers',
            name='password',
        ),
    ]
