# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0010_remove_subscribers_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailSent',
            new_name='photoUpload',
        ),
        migrations.RenameField(
            model_name='photoupload',
            old_name='post_id',
            new_name='username',
        ),
    ]
